server:
  port: 8082
spring:
  application:
    name: student_sb-mapping-one_to_one
  datasource:
    url: jdbc:mysql://localhost:3306/javaexpress
    username: root	
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
     hibernate:
      format_sql:true    
    
   